################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Application/Display \
Application/lvgl/demos/benchmark/assets \
Application/lvgl/demos/benchmark \
Application/lvgl/demos/ebike/generated \
Application/lvgl/demos/ebike \
Application/lvgl/demos/ebike/translations \
Application/lvgl/demos/flex_layout \
Application/lvgl/demos/high_res/fonts \
Application/lvgl/demos/high_res \
Application/lvgl/demos/keypad_encoder \
Application/lvgl/demos \
Application/lvgl/demos/multilang/assets/avatars \
Application/lvgl/demos/multilang/assets/emojis \
Application/lvgl/demos/multilang/assets/fonts \
Application/lvgl/demos/multilang/assets \
Application/lvgl/demos/multilang \
Application/lvgl/demos/music/assets \
Application/lvgl/demos/music \
Application/lvgl/demos/render/assets \
Application/lvgl/demos/render \
Application/lvgl/demos/scroll \
Application/lvgl/demos/stress \
Application/lvgl/demos/transform/assets \
Application/lvgl/demos/transform \
Application/lvgl/demos/vector_graphic/assets \
Application/lvgl/demos/vector_graphic \
Application/lvgl/demos/widgets/assets \
Application/lvgl/demos/widgets \
Application/lvgl/env_support/pikascript \
Application/lvgl/env_support/rt-thread \
Application/lvgl/env_support/rt-thread/squareline \
Application/lvgl/examples/anim \
Application/lvgl/examples/assets \
Application/lvgl/examples/assets/emoji \
Application/lvgl/examples/event \
Application/lvgl/examples/get_started \
Application/lvgl/examples/layouts/flex \
Application/lvgl/examples/layouts/grid \
Application/lvgl/examples/libs/barcode \
Application/lvgl/examples/libs/bmp \
Application/lvgl/examples/libs/ffmpeg \
Application/lvgl/examples/libs/freetype \
Application/lvgl/examples/libs/gif \
Application/lvgl/examples/libs/libjpeg_turbo \
Application/lvgl/examples/libs/libpng \
Application/lvgl/examples/libs/lodepng \
Application/lvgl/examples/libs/qrcode \
Application/lvgl/examples/libs/rlottie \
Application/lvgl/examples/libs/svg \
Application/lvgl/examples/libs/tiny_ttf \
Application/lvgl/examples/libs/tjpgd \
Application/lvgl/examples/others/file_explorer \
Application/lvgl/examples/others/font_manager \
Application/lvgl/examples/others/fragment \
Application/lvgl/examples/others/gestures \
Application/lvgl/examples/others/gridnav \
Application/lvgl/examples/others/ime \
Application/lvgl/examples/others/imgfont \
Application/lvgl/examples/others/monkey \
Application/lvgl/examples/others/observer \
Application/lvgl/examples/others/snapshot \
Application/lvgl/examples/others/xml \
Application/lvgl/examples/porting \
Application/lvgl/examples/porting/osal \
Application/lvgl/examples/scroll \
Application/lvgl/examples/styles \
Application/lvgl/examples/widgets/animimg \
Application/lvgl/examples/widgets/arc \
Application/lvgl/examples/widgets/bar \
Application/lvgl/examples/widgets/button \
Application/lvgl/examples/widgets/buttonmatrix \
Application/lvgl/examples/widgets/calendar \
Application/lvgl/examples/widgets/canvas \
Application/lvgl/examples/widgets/chart \
Application/lvgl/examples/widgets/checkbox \
Application/lvgl/examples/widgets/dropdown \
Application/lvgl/examples/widgets/image \
Application/lvgl/examples/widgets/imagebutton \
Application/lvgl/examples/widgets/keyboard \
Application/lvgl/examples/widgets/label \
Application/lvgl/examples/widgets/led \
Application/lvgl/examples/widgets/line \
Application/lvgl/examples/widgets/list \
Application/lvgl/examples/widgets/lottie \
Application/lvgl/examples/widgets/menu \
Application/lvgl/examples/widgets/msgbox \
Application/lvgl/examples/widgets/obj \
Application/lvgl/examples/widgets/roller \
Application/lvgl/examples/widgets/scale \
Application/lvgl/examples/widgets/slider \
Application/lvgl/examples/widgets/span \
Application/lvgl/examples/widgets/spinbox \
Application/lvgl/examples/widgets/spinner \
Application/lvgl/examples/widgets/switch \
Application/lvgl/examples/widgets/table \
Application/lvgl/examples/widgets/tabview \
Application/lvgl/examples/widgets/textarea \
Application/lvgl/examples/widgets/tileview \
Application/lvgl/examples/widgets/win \
Application/lvgl/src/core \
Application/lvgl/src/display \
Application/lvgl/src/draw/dma2d \
Application/lvgl/src/draw \
Application/lvgl/src/draw/nema_gfx \
Application/lvgl/src/draw/nxp/pxp \
Application/lvgl/src/draw/nxp/vglite \
Application/lvgl/src/draw/opengles \
Application/lvgl/src/draw/renesas/dave2d \
Application/lvgl/src/draw/sdl \
Application/lvgl/src/draw/sw/blend/helium \
Application/lvgl/src/draw/sw/blend \
Application/lvgl/src/draw/sw/blend/neon \
Application/lvgl/src/draw/sw \
Application/lvgl/src/draw/vg_lite \
Application/lvgl/src/drivers/display/drm \
Application/lvgl/src/drivers/display/fb \
Application/lvgl/src/drivers/display/ili9341 \
Application/lvgl/src/drivers/display/lcd \
Application/lvgl/src/drivers/display/renesas_glcdc \
Application/lvgl/src/drivers/display/st7735 \
Application/lvgl/src/drivers/display/st7789 \
Application/lvgl/src/drivers/display/st7796 \
Application/lvgl/src/drivers/display/st_ltdc \
Application/lvgl/src/drivers/evdev \
Application/lvgl/src/drivers/glfw \
Application/lvgl/src/drivers/libinput \
Application/lvgl/src/drivers/nuttx \
Application/lvgl/src/drivers/qnx \
Application/lvgl/src/drivers/sdl \
Application/lvgl/src/drivers/wayland \
Application/lvgl/src/drivers/windows \
Application/lvgl/src/drivers/x11 \
Application/lvgl/src/font \
Application/lvgl/src/indev \
Application/lvgl/src/layouts/flex \
Application/lvgl/src/layouts/grid \
Application/lvgl/src/layouts \
Application/lvgl/src/libs/barcode \
Application/lvgl/src/libs/bin_decoder \
Application/lvgl/src/libs/bmp \
Application/lvgl/src/libs/expat \
Application/lvgl/src/libs/ffmpeg \
Application/lvgl/src/libs/freetype \
Application/lvgl/src/libs/fsdrv \
Application/lvgl/src/libs/gif \
Application/lvgl/src/libs/libjpeg_turbo \
Application/lvgl/src/libs/libpng \
Application/lvgl/src/libs/lodepng \
Application/lvgl/src/libs/lz4 \
Application/lvgl/src/libs/qrcode \
Application/lvgl/src/libs/rle \
Application/lvgl/src/libs/rlottie \
Application/lvgl/src/libs/svg \
Application/lvgl/src/libs/tiny_ttf \
Application/lvgl/src/libs/tjpgd \
Application/lvgl/src \
Application/lvgl/src/misc/cache \
Application/lvgl/src/misc \
Application/lvgl/src/osal \
Application/lvgl/src/others/file_explorer \
Application/lvgl/src/others/font_manager \
Application/lvgl/src/others/fragment \
Application/lvgl/src/others/gridnav \
Application/lvgl/src/others/ime \
Application/lvgl/src/others/imgfont \
Application/lvgl/src/others/monkey \
Application/lvgl/src/others/observer \
Application/lvgl/src/others/snapshot \
Application/lvgl/src/others/sysmon \
Application/lvgl/src/others/vg_lite_tvg \
Application/lvgl/src/others/xml \
Application/lvgl/src/others/xml/parsers \
Application/lvgl/src/stdlib/builtin \
Application/lvgl/src/stdlib/clib \
Application/lvgl/src/stdlib \
Application/lvgl/src/stdlib/micropython \
Application/lvgl/src/stdlib/rtthread \
Application/lvgl/src/themes/default \
Application/lvgl/src/themes \
Application/lvgl/src/themes/mono \
Application/lvgl/src/themes/simple \
Application/lvgl/src/tick \
Application/lvgl/src/widgets/animimage \
Application/lvgl/src/widgets/arc \
Application/lvgl/src/widgets/bar \
Application/lvgl/src/widgets/button \
Application/lvgl/src/widgets/buttonmatrix \
Application/lvgl/src/widgets/calendar \
Application/lvgl/src/widgets/canvas \
Application/lvgl/src/widgets/chart \
Application/lvgl/src/widgets/checkbox \
Application/lvgl/src/widgets/dropdown \
Application/lvgl/src/widgets/image \
Application/lvgl/src/widgets/imagebutton \
Application/lvgl/src/widgets/keyboard \
Application/lvgl/src/widgets/label \
Application/lvgl/src/widgets/led \
Application/lvgl/src/widgets/line \
Application/lvgl/src/widgets/list \
Application/lvgl/src/widgets/lottie \
Application/lvgl/src/widgets/menu \
Application/lvgl/src/widgets/msgbox \
Application/lvgl/src/widgets/objx_templ \
Application/lvgl/src/widgets/property \
Application/lvgl/src/widgets/roller \
Application/lvgl/src/widgets/scale \
Application/lvgl/src/widgets/slider \
Application/lvgl/src/widgets/span \
Application/lvgl/src/widgets/spinbox \
Application/lvgl/src/widgets/spinner \
Application/lvgl/src/widgets/switch \
Application/lvgl/src/widgets/table \
Application/lvgl/src/widgets/tabview \
Application/lvgl/src/widgets/textarea \
Application/lvgl/src/widgets/tileview \
Application/lvgl/src/widgets/win \
Application/lvgl/tests/makefile \
Application/lvgl/tests/makefile_uefi \
Application/lvgl/tests/src \
Application/lvgl/tests/src/test_assets \
Application/lvgl/tests/src/test_cases \
Application/lvgl/tests/src/test_cases/cache \
Application/lvgl/tests/src/test_cases/draw \
Application/lvgl/tests/src/test_cases/libs \
Application/lvgl/tests/src/test_cases/widgets \
Application/lvgl/tests/src/test_cases/xml \
Application/lvgl/tests/src/test_libs/rnd_unicodes \
Application/lvgl/tests/src/test_libs/rnd_unicodes/rnd_unicodes/src \
Application/lvgl/tests/test_images/stride_align1/LZ4 \
Application/lvgl/tests/test_images/stride_align1/RLE \
Application/lvgl/tests/test_images/stride_align1/UNCOMPRESSED \
Application/lvgl/tests/test_images/stride_align64/LZ4 \
Application/lvgl/tests/test_images/stride_align64/RLE \
Application/lvgl/tests/test_images/stride_align64/UNCOMPRESSED \
Application/lvgl/tests/unity \
Application/ui \
Core/Src \
Core/Startup \
Drivers/STM32G4xx_HAL_Driver/Src \
Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src \
Middlewares/ST/STM32_USB_Device_Library/Core/Src \
System \
USB_Device/App \
USB_Device/Target \

