#ifndef EEZ_LVGL_UI_VARS_H
#define EEZ_LVGL_UI_VARS_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

// enum declarations



// Flow global variables

enum FlowGlobalVariables {
    FLOW_GLOBAL_VARIABLE_WHEEL = 0,
    FLOW_GLOBAL_VARIABLE_THROTTLE = 1,
    FLOW_GLOBAL_VARIABLE_BRAKE = 2,
    FLOW_GLOBAL_VARIABLE_CLUTCH = 3,
    FLOW_GLOBAL_VARIABLE_JOY_X = 4,
    FLOW_GLOBAL_VARIABLE_JOY_Y = 5,
    FLOW_GLOBAL_VARIABLE_LH_X = 6,
    FLOW_GLOBAL_VARIABLE_LH_Y = 7,
    FLOW_GLOBAL_VARIABLE_LH_R = 8,
    FLOW_GLOBAL_VARIABLE_FS25_CLICK1 = 9,
    FLOW_GLOBAL_VARIABLE_FS25_CLICK2 = 10,
    FLOW_GLOBAL_VARIABLE_FS25_CLICK3 = 11,
    FLOW_GLOBAL_VARIABLE_FS25_CLICK4 = 12,
    FLOW_GLOBAL_VARIABLE_FS25_SWITCH1 = 13,
    FLOW_GLOBAL_VARIABLE_FS25_SWITCH2 = 14,
    FLOW_GLOBAL_VARIABLE_FS25_SWITCH3 = 15,
    FLOW_GLOBAL_VARIABLE_FS25_SWITCH4 = 16,
    FLOW_GLOBAL_VARIABLE_FS25_SLIDER1 = 17,
    FLOW_GLOBAL_VARIABLE_FS25_SLIDER2 = 18,
    FLOW_GLOBAL_VARIABLE_FS25_SLIDER3 = 19,
    FLOW_GLOBAL_VARIABLE_FS25_SLIDER4 = 20,
    FLOW_GLOBAL_VARIABLE_FS25_CLICK_BACK = 21,
    FLOW_GLOBAL_VARIABLE_CALIBRATION_STATUS = 22,
    FLOW_GLOBAL_VARIABLE_CALIBRATION_VALUES = 23,
    FLOW_GLOBAL_VARIABLE_BTN_JOY = 24,
    FLOW_GLOBAL_VARIABLE_BTN_ESC = 25,
    FLOW_GLOBAL_VARIABLE_BTN_OK = 26,
    FLOW_GLOBAL_VARIABLE_BTN_UP = 27,
    FLOW_GLOBAL_VARIABLE_BTN_LEFT = 28,
    FLOW_GLOBAL_VARIABLE_BTN_RIGHT = 29,
    FLOW_GLOBAL_VARIABLE_BTN_DOWN = 30,
    FLOW_GLOBAL_VARIABLE_LH_BTN1 = 31,
    FLOW_GLOBAL_VARIABLE_LH_BTN2 = 32,
    FLOW_GLOBAL_VARIABLE_BASE_BTN1 = 33,
    FLOW_GLOBAL_VARIABLE_BASE_BTN2 = 34,
    FLOW_GLOBAL_VARIABLE_BASE_BTN3 = 35,
    FLOW_GLOBAL_VARIABLE_BASE_BTN4 = 36,
    FLOW_GLOBAL_VARIABLE_SHIFTER_L = 37,
    FLOW_GLOBAL_VARIABLE_SHIFTER_R = 38,
    FLOW_GLOBAL_VARIABLE_FORCE_FEEDBACK_STATUS = 39,
    FLOW_GLOBAL_VARIABLE_WHEEL_CALIB = 40,
    FLOW_GLOBAL_VARIABLE_PEDALS_CALIB = 41,
    FLOW_GLOBAL_VARIABLE_L_JOY_CALIB = 42,
    FLOW_GLOBAL_VARIABLE_MISKO_JOY_CALIB = 43,
    FLOW_GLOBAL_VARIABLE_FREQUENCIES = 44,
    FLOW_GLOBAL_VARIABLE_SELECTED_FREQUENCY_POSITION = 45,
    FLOW_GLOBAL_VARIABLE_FFB_STATE = 46,
    FLOW_GLOBAL_VARIABLE_BRIGHTNESS = 47,
    FLOW_GLOBAL_VARIABLE_DEADZONE = 48,
    FLOW_GLOBAL_VARIABLE_DEADZONE_CHAR = 49,
    FLOW_GLOBAL_VARIABLE_AXIS_MIN_MAX = 50,
    FLOW_GLOBAL_VARIABLE_FFB_SETTINGS = 51,
    FLOW_GLOBAL_VARIABLE_SETTING_VALUE = 52,
    FLOW_GLOBAL_VARIABLE_FFB_SETTINGS_SELECTED = 53
};

// Native global variables



#ifdef __cplusplus
}
#endif

#endif /*EEZ_LVGL_UI_VARS_H*/